### ISSUE TITLE
Backups fail for deployments using HPA randomly

### ISSUE THREAD

**Issue by echel0n** [heptio/velero#1770] opened 2019-08-17 20:37 UTC
**Describe the problem/challenge you have**
Deployments with HPA can cause issues with backups and not being able to find pod during backup phase.

**Logs:**
```
velero backup logs backup-2019-08-17-12-58-38 |grep error
time="2019-08-17T20:02:39Z" level=info msg="2 errors encountered backup up item" backup=velero/backup-2019-08-17-12-58-38 group=v1 logSource="pkg/backup/resource_backupper.go:260" name=discourse-9cb5c9c84-bsfsz namespace= resource=pods
time="2019-08-17T20:02:39Z" level=error msg="Error backing up item" backup=velero/backup-2019-08-17-12-58-38 error="pod volume backup failed: error getting pod: pod \"discourse-9cb5c9c84-bsfsz\" not found" error.file="/go/src/github.com/heptio/velero/pkg/restic/backupper.go:175" error.function="github.com/heptio/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=discourse-9cb5c9c84-bsfsz namespace= resource=pods
time="2019-08-17T20:02:39Z" level=error msg="Error backing up item" backup=velero/backup-2019-08-17-12-58-38 error="pod volume backup failed: error getting pod: pod \"discourse-9cb5c9c84-bsfsz\" not found" error.file="/go/src/github.com/heptio/velero/pkg/restic/backupper.go:175" error.function="github.com/heptio/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=discourse-9cb5c9c84-bsfsz namespace= resource=pods
time="2019-08-17T20:03:47Z" level=info msg="2 errors encountered backup up item" backup=velero/backup-2019-08-17-12-58-38 group=v1 logSource="pkg/backup/resource_backupper.go:260" name=discourse-9cb5c9c84-pv6pz namespace= resource=pods
time="2019-08-17T20:03:47Z" level=error msg="Error backing up item" backup=velero/backup-2019-08-17-12-58-38 error="pod volume backup failed: error getting pod: pod \"discourse-9cb5c9c84-pv6pz\" not found" error.file="/go/src/github.com/heptio/velero/pkg/restic/backupper.go:175" error.function="github.com/heptio/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=discourse-9cb5c9c84-pv6pz namespace= resource=pods
time="2019-08-17T20:03:47Z" level=error msg="Error backing up item" backup=velero/backup-2019-08-17-12-58-38 error="pod volume backup failed: error getting pod: pod \"discourse-9cb5c9c84-pv6pz\" not found" error.file="/go/src/github.com/heptio/velero/pkg/restic/backupper.go:175" error.function="github.com/heptio/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=discourse-9cb5c9c84-pv6pz namespace= resource=pods
```
**Environment:**
Velero version (use velero version): v1.1.0-beta.2
Kubernetes version (use kubectl version): v1.15.0
Kubernetes installer & version: kubeadm / v1.15.0
Cloud provider or hardware configuration: 3 node cluster
OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS

**Comment by echel0n** [comment] 2019-08-26 02:40
This issue is still present in latest v1.1.0 release

**Comment by skriss** [comment] 2019-09-04 19:19
@echel0n just to clarify - is the problem you're having that some pods are being deleted by the HPA in the middle of a Velero backup, and that causes Velero to error here?

**Comment by echel0n** [comment] 2019-09-04 19:30
@skriss yes it does appear that during the backup process the HPA was killing the pods, this was due to fluctuating memory levels, I've since set HPA to only monitor CPU usage and resolved the issue in that manner but still the problem here is that there seems to be no locking of the pods to prevent outside termination of them, perhaps setting pods with critical annotation would resolve this issue as well as my other issue related to descheduler ?

**Comment by skriss** [comment] 2019-09-04 19:48
Yes, definitely sounds like a similar issue. If it's okay with you, I'll close this issue and use the other one to track the general feature request?

**Comment by echel0n** [comment] 2019-09-04 19:59
Sure, sounds good to me.

**Comment by skriss** [comment] 2019-09-04 20:03
closing as dupe of #1752

**Closed by skriss** 2019-09-04 20:03 UTC
Labels: Duplicate
