### ISSUE TITLE
Precedence of Kubeconfig

### ISSUE THREAD

**Issue by rclayton-the-terrible** [heptio/velero#1686] opened 2019-07-20 16:02 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Supplying config file location (via an environment variable or `--kubeconfig` flag) does not work:

```
velero install \
    --kubeconfig <path-to-config> \
    --provider aws \
    --bucket $BUCKET \
    --secret-file ./credentials-velero \
    --backup-location-config region=$REGION \
    --snapshot-location-config region=$REGION
```

```
KUBECONFIG=<path-to-config> velero install \
    --provider aws \
    --bucket $BUCKET \
    --secret-file ./credentials-velero \
    --backup-location-config region=$REGION \
    --snapshot-location-config region=$REGION
```

In both strategies, I get the error:

```
Error installing Velero. Use `kubectl logs deploy/velero -n velero` to check the deploy logs: Error creating resource CustomResourceDefinition/podvolumebackups.velero.io: Post https://192.168.99.100:8443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions: dial tcp 192.168.99.100:8443: i/o timeout
```

I'm guessing that my Minikube config (`~/.kube/config`) is taking precedence over the flag and env var.

I am 100% certain my path to my kubeconfig file works (I use it for `kubectl`, `argo` and `helm`).  

**What did you expect to happen:**

I'm not sure if the flag or env var are being ignored, but I would assume when supplying the `--kubeconfig` it would override any other config.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

This was on cluster install (so no deploy logs).  I was successfully able to install by moving my custom cluster config to `~/.kube/config`.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 1.0.0
- Kubernetes version (use `kubectl version`): 1.10
- Kubernetes installer & version: ?
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Client - OSX/Darwin

**Comment by skriss** [comment] 2019-07-22 15:23
Thanks for logging the issue @rclayton-the-terrible -- it looks like this is a duplicate of #1651, which has been fixed in `master` via #1656. We'll be releasing this as part of v1.1 within the next ~month. Closing this out but feel free to reach out again as needed.

**Closed by skriss** 2019-07-22 15:23 UTC
Labels: Bug, Duplicate
