### ISSUE TITLE
Custom Resources are not restored

### ISSUE THREAD

**Issue by suleymanakbas91** [heptio/velero#1633] opened 2019-07-09 09:20 UTC
**What steps did you take and what happened:**
I took a full backup including all the resources on the cluster using Velero. 

I created another cluster and installed Velero using:
`velero install --provider gcp --bucket <bucket> --secret-file <secret-file> --restore-only`

I requested a restore:

`velero restore create --from-backup <backup-name> --include-resources --include-cluster-resources --restore-volumes`

Velero restores everything (including the corresponding CRDs) except for the Custom Resources. Although the restore status was completed, I waited a couple of hours to see if they would appear. But, they didn't. 

Then, I just tried to run the restore command one more time and realized that Custom Resources were restored this time. Of course, it ended with many warnings saying all the other resources have already existed on the cluster.

**What did you expect to happen:**
Velero restores everything from backup including the Custom Resources.

**The output of the following commands will help us better understand what's going on**:

* `kubectl logs deployment/velero -n velero`
[velero-pod-logs.txt](https://github.com/heptio/velero/files/3372160/velero-pod-logs.txt)

**Environment:**

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.12.9-gke.7
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment] 2019-07-09 14:37
@suleymanakbas91 it sounds like you're probably running into #964 / #1350 -- TLDR is that Velero doesn't wait for the CRDs to be "ready" after restoring them, so it's possible that by the time it tries to restore the custom resource instances, the CRDs aren't yet ready. 

You could do a two-stage restore similar to what you already did -- in the first restore, use the `--exclude-resources` flag to exclude the custom resources from restore. After that completes and you can verify that the CRDs are ready, do another restore using `--include-resources` to specify only the custom resources.

**Comment by suleymanakbas91** [comment] 2019-07-12 14:33
Thanks for the suggestion @skriss. As you suggested, I divided the restore process into two commands. First, I restore the CRDs (also services and endpoints for another problem with Istio): 
```
velero restore create --from-backup kyma-backup --include-resources customresourcedefinitions.apiextensions.k8s.io,services,endpoints --include-cluster-resources
```
After this restore gets completed, I wait for a while to ensure CRDs are ready and then run this to restore the rest:
```
velero restore create --from-backup kyma-backup --exclude-resources customresourcedefinitions.apiextensions.k8s.io,services,endpoints --include-cluster-resources --restore-volumes
```
This second restore does not behave consistent. Sometimes it restores all the Custom Resources, sometimes it does not restore some of the Custom Resources. If I run this second command again, it restores all the remainings.

You can find the logs of an example execution here:
[first_part.log](https://github.com/heptio/velero/files/3386787/first_part.log)
[second_part.log](https://github.com/heptio/velero/files/3386788/second_part.log)
[second_part_repeat.log](https://github.com/heptio/velero/files/3386789/second_part_repeat.log)
 
In my first try, it does not restore any of the VirtualService resources. Then, I run the second command again and puff, there they are.

**Comment by skriss** [comment] 2019-08-29 20:33
It sounds like the CRDs may not have been fully ready when the second restore was run, but I'd need to see details of the CRDs to be sure.

I'm going to close this issue as a duplicate of #964 where we're tracking the enhancement request.

**Closed by skriss** 2019-08-29 20:33 UTC
