### ISSUE TITLE
Velero backup full cluster doesnt appear to backup/restore etcd, and state of cluster after restore isn't same as cluster before backup

### ISSUE THREAD

**Issue by eddeh83** [heptio/velero#1610] opened 2019-06-27 10:14 UTC
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I wanted to test whether Velero would backup and restore a cluster after I had destroyed etcd.

I backed up my Kops Kubernetes cluster which was successful

``` bash
[centos@ee78cb168c41 tmp]$ velero backup create whole-cluster-backup
Backup request "whole-cluster-backup" submitted successfully.

[centos@ee78cb168c41 tmp]$ velero backup logs whole-cluster-backup | grep -i etcd
time="2019-06-27T08:30:52Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-20-96.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Executing custom action" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:307" name=etcd-server-events-ip-10-0-20-96.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-24-50.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Executing custom action" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:307" name=etcd-server-events-ip-10-0-24-50.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-25-29.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Executing custom action" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:307" name=etcd-server-events-ip-10-0-25-29.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-20-96.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Executing custom action" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:307" name=etcd-server-ip-10-0-20-96.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-24-50.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Executing custom action" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:307" name=etcd-server-ip-10-0-24-50.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-25-29.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:52Z" level=info msg="Executing custom action" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:307" name=etcd-server-ip-10-0-25-29.ec2.internal namespace=kube-system resource=pods
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-25-29.ec2.internal.15abfffe2babdaf7 namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-25-29.ec2.internal.15ac0001334ff44d namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-25-29.ec2.internal.15ac000136dccf9e namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-events-ip-10-0-25-29.ec2.internal.15ac00013f832970 namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-25-29.ec2.internal.15abfffe26d88482 namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-25-29.ec2.internal.15abffffd583e435 namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-25-29.ec2.internal.15abffffd85af32a namespace=kube-system resource=events
time="2019-06-27T08:30:54Z" level=info msg="Backing up item" backup=velero/whole-cluster-backup group=v1 logSource="pkg/backup/item_backupper.go:163" name=etcd-server-ip-10-0-25-29.ec2.internal.15abffffdeab4388 namespace=kube-system resource=events
```

Then created some change on the cluster, as well as eventually destroying etcd on one of the nodes.

``` bash

[centos@ee78cb168c41 tmp]$ kubectl apply -f nginx_with_pv.yaml
namespace/nginx-example created
persistentvolume/nginx-logs-volume created
persistentvolumeclaim/nginx-logs created
deployment.apps/nginx-deployment created
service/my-nginx created
[centos@ee78cb168c41 tmp]$
[centos@ee78cb168c41 tmp]$
[centos@ee78cb168c41 tmp]$ kubectl create secret generic db-user-pass-bloop --from-file=./username.txt --from-file=./password.txt --namespace nginx-example
secret/db-user-pass-bloop created
[centos@ee78cb168c41 tmp]$ kops validate cluster
Using cluster from kubectl context: kops-cluster-sb.platformdxc-sb.internal

Validating cluster kops-cluster-sb.platformdxc-sb.internal

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1a       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_A
master-us-east-1b       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_B
master-us-east-1c       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_C
node-us-east-1a         Node    t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_A
node-us-east-1b         Node    t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_B
node-us-east-1c         Node    t2.medium       0       0       PLATFORM_DXC_NCL_PRIVATE_AZ_C
```

Broke etcd

``` bash

root@ip-10-0-25-29:/mnt/master-vol-0828062c8d014da1f/var/etcd/data/member/wal# rm 0000000000000000-0000000000000000.wal

root@ip-10-0-25-29:/mnt/master-vol-06daabd4279eba42e/var/etcd/data-events/member/wal# rm -rf 0000000000000000-0000000000000000.wal

[centos@ee78cb168c41 tmp]$ kubectl delete pod etcd-server-events-ip-10-0-25-29.ec2.internal kube-apiserver-ip-10-0-25-29.ec2.internal -n kube-system
pod "etcd-server-events-ip-10-0-25-29.ec2.internal" deleted
pod "kube-apiserver-ip-10-0-25-29.ec2.internal" deleted

[centos@ee78cb168c41 tmp]$ kops validate cluster
Using cluster from kubectl context: kops-cluster-sb.platformdxc-sb.internal

Validating cluster kops-cluster-sb.platformdxc-sb.internal

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1a       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_A
master-us-east-1b       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_B
master-us-east-1c       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_C
node-us-east-1a         Node    t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_A
node-us-east-1b         Node    t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_B
node-us-east-1c         Node    t2.medium       0       0       PLATFORM_DXC_NCL_PRIVATE_AZ_C

NODE STATUS
NAME                            ROLE    READY
ip-10-0-20-96.ec2.internal      master  True
ip-10-0-24-132.ec2.internal     node    True
ip-10-0-24-50.ec2.internal      master  True
ip-10-0-25-174.ec2.internal     node    True
ip-10-0-25-29.ec2.internal      master  Unknown

VALIDATION ERRORS
KIND    NAME                            MESSAGE
Node    ip-10-0-25-29.ec2.internal      master "ip-10-0-25-29.ec2.internal" is not ready

```

Restore the backup 

``` bash 

[centos@ee78cb168c41 tmp]$ velero restore create --from-backup whole-cluster-backup
Restore request "whole-cluster-backup-20190627084228" submitted successfully.
```

Wait a while

```bash

[centos@ee78cb168c41 tmp]$ kops validate cluster
Using cluster from kubectl context: kops-cluster-sb.platformdxc-sb.internal

Validating cluster kops-cluster-sb.platformdxc-sb.internal

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-us-east-1a       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_A
master-us-east-1b       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_B
master-us-east-1c       Master  t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_C
node-us-east-1a         Node    t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_A
node-us-east-1b         Node    t2.medium       1       1       PLATFORM_DXC_NCL_PRIVATE_AZ_B
node-us-east-1c         Node    t2.medium       0       0       PLATFORM_DXC_NCL_PRIVATE_AZ_C

NODE STATUS
NAME                            ROLE    READY
ip-10-0-20-96.ec2.internal      master  True
ip-10-0-24-132.ec2.internal     node    True
ip-10-0-24-50.ec2.internal      master  True
ip-10-0-25-174.ec2.internal     node    True
ip-10-0-25-29.ec2.internal      master  Unknown

VALIDATION ERRORS
KIND    NAME                            MESSAGE
Node    ip-10-0-25-29.ec2.internal      master "ip-10-0-25-29.ec2.internal" is not ready

Validation Failed
[centos@ee78cb168c41 tmp]$ kubectl get pods --all-namespaces
NAMESPACE       NAME                                                 READY     STATUS     RESTARTS   AGE
kube-system     calico-kube-controllers-5866c4dfdb-sb47r             1/1       Running    0          32m
kube-system     calico-node-54ks8                                    2/2       Running    0          32m
kube-system     calico-node-65wlt                                    2/2       Running    0          30m
kube-system     calico-node-dd657                                    2/2       Running    0          31m
kube-system     calico-node-gv5jx                                    2/2       NodeLost   0          32m
kube-system     calico-node-kl5n2                                    2/2       Running    0          32m
kube-system     dns-controller-749f6b9f5-6h2fx                       1/1       Running    0          32m
kube-system     etcd-server-events-ip-10-0-20-96.ec2.internal        1/1       Running    0          31m
kube-system     etcd-server-events-ip-10-0-24-50.ec2.internal        1/1       Running    0          31m
kube-system     etcd-server-events-ip-10-0-25-29.ec2.internal        1/1       Unknown    0          31m
kube-system     etcd-server-ip-10-0-20-96.ec2.internal               1/1       Running    0          32m
kube-system     etcd-server-ip-10-0-24-50.ec2.internal               1/1       Running    0          31m
kube-system     etcd-server-ip-10-0-25-29.ec2.internal               1/1       Unknown    0          31m
kube-system     kube-apiserver-ip-10-0-20-96.ec2.internal            1/1       Running    0          31m
kube-system     kube-apiserver-ip-10-0-24-50.ec2.internal            1/1       Running    0          31m
kube-system     kube-apiserver-ip-10-0-25-29.ec2.internal            1/1       Unknown    0          31m
kube-system     kube-controller-manager-ip-10-0-20-96.ec2.internal   1/1       Running    0          31m
kube-system     kube-controller-manager-ip-10-0-24-50.ec2.internal   1/1       Running    0          31m
kube-system     kube-controller-manager-ip-10-0-25-29.ec2.internal   1/1       Unknown    0          31m
kube-system     kube-dns-6b4f4b544c-4pq5x                            3/3       Running    0          32m
kube-system     kube-dns-6b4f4b544c-zf9lh                            3/3       Running    0          30m
kube-system     kube-dns-autoscaler-6b658bd4d5-v4jbl                 1/1       Running    0          32m
kube-system     kube-proxy-ip-10-0-20-96.ec2.internal                1/1       Running    0          31m
kube-system     kube-proxy-ip-10-0-24-132.ec2.internal               1/1       Running    0          29m
kube-system     kube-proxy-ip-10-0-24-50.ec2.internal                1/1       Running    0          31m
kube-system     kube-proxy-ip-10-0-25-174.ec2.internal               1/1       Running    0          29m
kube-system     kube-proxy-ip-10-0-25-29.ec2.internal                1/1       Unknown    0          31m
kube-system     kube-scheduler-ip-10-0-20-96.ec2.internal            1/1       Running    0          31m
kube-system     kube-scheduler-ip-10-0-24-50.ec2.internal            1/1       Running    0          31m
kube-system     kube-scheduler-ip-10-0-25-29.ec2.internal            1/1       Unknown    0          31m
nginx-example   nginx-deployment-fb4f5ccc5-cbdwm                     1/1       Running    0          9m
velero          velero-6bc88f8ff6-qs5q4                              1/1       Running    0          16m
[centos@ee78cb168c41 tmp]$ velero get backups


[centos@ee78cb168c41 mnt]$ kubectl get secrets -n nginx-example
NAME                  TYPE                                  DATA      AGE
db-user-pass-bloop    Opaque                                2         1h
default-token-c2l6x   kubernetes.io/service-account-token   3         1h


ls -lrt /mnt/master-vol-0828062c8d014da1f/var/etcd/data/member/wal
total 0

 ls -lrt /mnt/master-vol-06daabd4279eba42e/var/etcd/data-events/member/wal
total 0
```

**What did you expect to happen:**

I expected etcd to be restored, and all changes I made after I took the backup to be wiped out (e.g creating the nginx-example namespace and the secret) 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

bash ```
[centos@ee78cb168c41 mnt]$ kubectl get backup whole-cluster-backup -n velero -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: 2019-06-27T08:30:51Z
  generation: 1
  labels:
    velero.io/storage-location: default
  name: whole-cluster-backup
  namespace: velero
  resourceVersion: "2585"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/whole-cluster-backup
  uid: df9fb834-98b5-11e9-84df-0a5b177607bc
spec:
  excludedNamespaces: null
  excludedResources: null
  hooks:
    resources: null
  includeClusterResources: null
  includedNamespaces:
  - '*'
  includedResources: null
  labelSelector: null
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
status:
  completionTimestamp: 2019-06-27T08:30:56Z
  errors: 0
  expiration: 2019-07-27T08:30:52Z
  phase: Completed
  startTimestamp: 2019-06-27T08:30:52Z
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0
  warnings: 0
```

velero backup logs whole-cluster-backup

* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`

``` bash
[centos@ee78cb168c41 mnt]$ velero restore describe whole-cluster-backup-20190627090422
Name:         whole-cluster-backup-20190627090422
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  Completed

Warnings:
  Velero:     <none>
  Cluster:    <none>
  Namespaces:
    default:      not restored: endpoints "kubernetes" already exists and is different from backed up version.
                  not restored: services "kubernetes" already exists and is different from backed up version.
    kube-system:  not restored: pods "calico-kube-controllers-5866c4dfdb-sb47r" already exists and is different from backed up version.
                  not restored: pods "calico-node-54ks8" already exists and is different from backed up version.
                  not restored: pods "calico-node-65wlt" already exists and is different from backed up version.
                  not restored: pods "calico-node-dd657" already exists and is different from backed up version.
                  not restored: pods "calico-node-gv5jx" already exists and is different from backed up version.
                  not restored: pods "calico-node-kl5n2" already exists and is different from backed up version.
                  not restored: pods "dns-controller-749f6b9f5-6h2fx" already exists and is different from backed up version.
                  not restored: pods "kube-dns-6b4f4b544c-4pq5x" already exists and is different from backed up version.
                  not restored: pods "kube-dns-6b4f4b544c-zf9lh" already exists and is different from backed up version.
                  not restored: pods "kube-dns-autoscaler-6b658bd4d5-v4jbl" already exists and is different from backed up version.
                  not restored: endpoints "kube-controller-manager" already exists and is different from backed up version.
                  not restored: endpoints "kube-scheduler" already exists and is different from backed up version.
                  not restored: services "kube-dns" already exists and is different from backed up version.
    velero:       not restored: pods "velero-6bc88f8ff6-qs5q4" already exists and is different from backed up version.

Backup:  whole-cluster-backup

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto
```

* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 

[centos@ee78cb168c41 mnt]$ velero version
Client:
        Version: v1.0.0
        Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb
Server:
        Version: v1.0.0

- Kubernetes version (use `kubectl version`):

[centos@ee78cb168c41 mnt]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

[centos@ee78cb168c41 mnt]$ kops version
Version 1.11.0 (git-2c2042465)

- Kubernetes installer & version:
- Cloud provider or hardware configuration:

AWS

- OS (e.g. from `/etc/os-release`):

[centos@ee78cb168c41 mnt]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[Velero_backup_logs.txt](https://github.com/heptio/velero/files/3334094/Velero_backup_logs.txt)
[velero_deployment_logs.txt](https://github.com/heptio/velero/files/3334095/velero_deployment_logs.txt)
[velero_restore_logs.txt](https://github.com/heptio/velero/files/3334096/velero_restore_logs.txt)
[Velero_backup_logs.txt](https://github.com/heptio/velero/files/3334099/Velero_backup_logs.txt)
[velero_deployment_logs.txt](https://github.com/heptio/velero/files/3334100/velero_deployment_logs.txt)
[velero_restore_logs.txt](https://github.com/heptio/velero/files/3334101/velero_restore_logs.txt)

**Comment by skriss** [comment] 2019-07-03 16:11
@eddeh83 Velero won't delete any resources from your cluster (by design) - it'll simply apply whatever was in the backup to your API. So, if you have existing resources in the cluster that you want to replace, you'll need to delete them from the cluster first. We do have an issue in the backlog to delete resources before attempting to create them - see https://github.com/heptio/velero/issues/469 - and please add any comments you have there. Thanks!

**Comment by eddeh83** [comment] 2019-07-03 16:48
Thanks for that, appreciated. Do you know if velero can backup/restore etcd within a kops k8s cluster? Or if thats a feature to come?

**Comment by nrb** [comment] 2019-07-09 04:18
Velero doesn't operate directly on the etcd database backing Kubernetes - it instead interfaces with the Kubernetes API server.

**Comment by skriss** [comment] 2019-07-15 15:37
I'm closing this issue as it appears to have been responded to; feel free to reopen as needed.

**Closed by skriss** 2019-07-15 15:37 UTC
Labels: Question
