### ISSUE TITLE
Reconciliation as part of restore

### ISSUE THREAD

**Issue by saravanakumar-periyasamy** [heptio/velero#523] opened 2018-06-01 19:23 UTC
Use case: in cluster migration scenario, user likes to keep the resources in `destination` clusters in sync with `source` cluster. Which means, the restore process have to delete the resources in the destination cluster if its not part of the backup.

**Comment by ncdc** [comment] 2018-06-26 14:02
@rosskukulinski for PM review

**Comment by nrb** [comment] 2018-11-07 17:31
xref #469

**Comment by skriss** [comment] 2019-02-07 20:29
Closing this issue as a dupe of #469.

**Closed by skriss** 2019-02-07 20:29 UTC
Labels: Enhancement/User, Needs Product, Waiting for info
