### ISSUE TITLE
Wished to know does ark supports backup and restore from 1.8 to 1.10 version of kubernetes

### ISSUE THREAD

**Issue by Sam123ben** [heptio/velero#1182] opened 2019-02-05 12:31 UTC
We have a kubernetes cluster which is running on 1.8 version of k8s and wish to create a backup of my cluster and will then restore it to my new k8s 1.10 version of kubernetes cluster. Will the ark supports this. Bdw this utility rocks as its easy simple and does what it state.

Please do let me know if this can be done as we will then continue using it.

Regards

**Comment by ncdc** [comment] 2019-02-05 14:43
As long as the apiVersions for all the items in the backup are still present in the 1.10 cluster, we can do the restore. See https://github.com/heptio/ark/blob/bbc6caf7fe93faac57f3fc7652d816fb47cbf457/docs/about.md#backed-up-api-versions for more details.
________________________________

**Comment by Sam123ben** [comment] 2019-02-07 00:14
@ncdc Thanks for that information, but we are facing issues while trying to install the ark-server itself on the 1.8 version of kubernetes and also sometimes on the 1.10 as well.

helm upgrade --install ark-server --namespace backup ./helm-charts/ark-server -f $ENVIRONMENT_FOLDER/config/config.yml -f $ENVIRONMENT_FOLDER/config/secrets/secrets.yml
Release "ark-server" does not exist. Installing it now.
Error: object is being deleted: customresourcedefinitions.apiextensions.k8s.io "backups.ark.heptio.com" already exist

Any idea about the above issue?

Thanks in advance

**Comment by skriss** [comment] 2019-03-13 19:02
@Sam123ben this looks like a dupe of #1195 so I'm closing this one.  If that's not the case feel free to reopen.

**Closed by skriss** 2019-03-13 19:02 UTC
