### ISSUE TITLE
Status section in crd object is not restored

### ISSUE THREAD

**Issue by i300543** [heptio/velero#1788] opened 2019-08-22 14:42 UTC
**What steps did you take and what happened:**
We are trying to implement cluster migration for disaster recovery using velero.
In original cluster we back up some crd instances, and then try to restore them in the backup cluster.

**What did you expect to happen:**
we expect the  crd objects to be restored with the original status section,
instead they are restored without:

original crd yaml:
apiVersion: devx.sap.com/v1
kind: Workspace
metadata:
  annotations:
  ...
  name: ws-sdjqn
  namespace: workspaces
spec:
  extensions:
  ...
status:
  controllerID: webide-release-controller
  namespace: tight-barnacle
  suspended: false
  workspaceID: workspaces-ws-sdjqn

restored crd yaml:
apiVersion: devx.sap.com/v1
kind: Workspace
metadata:
  annotations:
    optionalExtensions: '[]'
    pack: Basic
    technicalExtensions: '[]'
  creationTimestamp: "2019-08-22T14:13:07Z"
  generation: 1
  labels:
    ...
  name: ws-sdjqn
  namespace: workspaces
spec:
  extensions:
  ...<spec content>

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
https://gist.github.com/i300543/dc8f10d26b1eea5929fb71dcd1bbe30f
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
Name:         crd-backup-20190822140849
Namespace:    velero
Labels:       velero.io/schedule-name=crd-backup
              velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  workspaces
  Excluded:  <none>

Resources:
  Included:        workspaces.devx.sap.com, configmaps
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  5m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-08-22 17:08:50 +0300 IDT
Completed:  2019-08-22 17:08:51 +0300 IDT

Expiration:  2019-08-22 17:13:50 +0300 IDT

Persistent Volumes: <none included>

* `velero backup logs <backupname>`
https://gist.github.com/i300543/1c6c12cf8e5f5d5657b0ccb5478a2d6f
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
Name:         crd-restore
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:     Completed
Warnings:  <error getting warnings: timed out waiting for download URL>

Errors:  <error getting errors: timed out waiting for download URL>

Backup:  crd-backup-20190822140849

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, backups.velero.io, restores.ark.heptio.com, restores.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

* `velero restore logs <restorename>`

https://gist.github.com/i300543/5b12779462a6f6b3b5603f3a7cfb6bf8

**Environment:**

- Velero version 1.0.0
- Kubernetes version 1.12.5
- Kubernetes installer & version:
- Cloud provider or hardware configuration: aws
- OS: Windows

**Comment by nrb** [comment] 2019-08-22 15:24
Thanks for the report @i300543! I think this is a duplicate of #1687

**Closed** 2019-08-22 15:25 UTC
