### ISSUE TITLE
doc-site-gen not working properly

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1245] opened 2019-02-28 21:03 UTC
Ran our private tool doc-gen-site to `add master` after a new release. Expected the contents of the `master/` folder in `gh-pages` to contain the updated docs from the `master` branch. Instead, it only deleted the `master/` directory in `gh-pages` and did nothing else.

Also, adding a new version did not strip the `docs/` from the new image links.

**Comment by nrb** [comment] 2019-02-28 22:27
I'm able to reproduce this

**Comment by nrb** [comment] 2019-02-28 22:30
Also verified that this does *not* happen on Contour, which updates as expected.

**Comment by carlisia** [comment] 2019-02-28 22:33
Thanks for checking. I wonder if it was due to the change on the `gen_version.sh` file.

**Comment by nrb** [comment] 2019-02-28 22:35
Yeah, I'm guessing it was. I'm fiddling with a test directory to see if I can replicate the behavior. It won't happen on versioned dirs right now, since `gen_version.sh` will error on an existing dir in that case.

**Comment by carlisia** [comment] 2019-02-28 22:37
Just delete the existing dir and spruce up the config.yml.

**Comment by nrb** [comment] 2019-02-28 22:43
```
x1c in /home/nrb/go/src/github.com/heptio/velero (git) gh-pages
% ./gen_version.sh master

x1c in /home/nrb/go/src/github.com/heptio/velero (git) gh-pages U
% git st
On branch gh-pages
Your branch and 'origin/gh-pages' have diverged,
and have 17 and 10 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   master/README.md
        modified:   master/about.md
```

Hm, works if `.gen_version.sh` is called directly. May have to dive into the doc-site-gen code

**Comment by carlisia** [comment] 2019-02-28 22:45
Oooood

**Comment by nrb** [comment] 2019-02-28 22:46
Yeah, I think this is a doc-site-gen issue. Maybe we open an issue there while we investigate.

**Comment by skriss** [comment] 2019-05-20 14:56
This is no longer relevant since we've moved to netlify, closing.

**Closed by skriss** 2019-05-20 14:56 UTC
Labels: Documentation
