### ISSUE TITLE
AKS full cluster backup error

### ISSUE THREAD

**Issue by ronsonblossom** [heptio/velero#1305] opened 2019-03-21 10:33 UTC
I tried taking a full cluster backup of AKS using below command:
velero backup create akstest1xzy

The backup is supposed to be complete successfully, but it failed
Status says failed with error below:
+====================+
time="2019-03-21T10:08:12Z" level=info msg="Backup completed with errors: clusterroles.rbac.authorization.k8s.io \"system:auth-delegator\" not found" backup=velero/akstest1xzy logSource="pkg/backup/backup.go:297"
+====================+
https://gist.github.com/ronsonblossom/1ee1c126438085d53a58affa3baa3a72

Same activity if I perform in a non AKS or standalone K8s cluster, Velero works fine

**Environment:**

- Velero version (use `velero version`): 
Client:
        Version: v0.11.0
        Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
Server:
        Version: v0.11.0

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.6", GitCommit:"ab91afd7062d4240e95e51ac00a18bd58fddd365", GitTreeState:"clean", BuildDate:"2019-02-26T12:49:28Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider : Azure Kuberenetes Service (AKS)

**Comment by skriss** [comment] 2019-03-21 14:53
I'm guessing that you have a clusterrolebinding that refers to this non-existent "system:auth-delegator" clusterrole somewhere. If you can find it and delete it, I'd expect the backup would go through successfully. However, I don't think this should cause a backup to be Failed.  You should still have a backup tarball in object storage, though, with everything it could back up.

**Comment by skriss** [comment] 2019-03-21 14:53
xref https://github.com/heptio/velero/issues/286#issuecomment-440382021

**Comment by skriss** [comment] 2019-04-17 22:21
closing this as it's currently working "as designed" -- i.e. any failure during the backup process results in the backup being `Failed` (although you may still get a restorable tarball in object storage). Note that as part of #1371, we'll introduce a "PartiallyFailed" phase to capture cases where some items failed to back up.

**Closed by skriss** 2019-04-17 22:21 UTC

**Comment by arianitu** [comment] 2019-04-25 16:06
I'm running into the same issue on AKS. In my cluster, `metrics-server` is half running, since `heapster` is running instead.

Perhaps AKS setup `metrics-server` incorrectly during an upgrade or something and we're running into this issue and it's a common bug in AKS.
