### ISSUE TITLE
Scheduler stops working after another deploy

### ISSUE THREAD

**Issue by mmuth** [heptio/velero#1160] opened 2019-01-11 15:59 UTC
**What steps did you take and what happened:**
We have ark setup an running fine on our production systems. However we noticed, that ark stops doing backups if we execute the kubectl apply again (our Jenkins deploys automatically when something changes in our ark repository). 

The minimal repro should be something like:
1. deploy ark. I have a minimal repro commited here with my deployment and everything: https://github.com/mmuth/ark-schedule-repro
2. watch ark doing backups as intended
3. deploy again with kubectl apply
4. schedule stops working (not neccessarly at once, but within the next hour). I can observe it via Prometheus or ark schedule get in the "last backup"-column. In the logs the line "scheduler is due, submitting backup" is not appearing anymore.

**What did you expect to happen:**
Backups should just be created according to the schedule.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
https://gist.github.com/mmuth/eb52b859e1e04c63e40c9151e744fe04

**Anything else you would like to add:**
... if I delete the ark pod, then the schedule will work again.

And here is a screenshot where you can see the success counter of ark (the point where the steps stop to increase is close to the moment where I executed the deploy a second time).

![image](https://user-images.githubusercontent.com/15966543/51043937-334b7c80-15c0-11e9-8a6d-4cb50610e766.png)

**Environment:**

- Ark version (use `ark version`): 
```
Version: v0.10.0
Git commit: v0.10.0
Git tree state: clean
```
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.9", GitCommit:"e6ab4ee54f71e7a403cc733534bab86fd959ecb7", GitTreeState:"clean", BuildDate:"2018-10-16T12:14:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: kops, Version 1.10.0 (git-8b52ea6d1)
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`):
```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by mmuth** [comment] 2019-01-14 09:59
Hi @skriss 

Thanks for your quick response. Just executed my reproduction again. Here is the full server log with the debug option you described: https://gist.github.com/mmuth/568e0b155d85956851fc4d11b6ed267b

Now I can see there is a line `Schedule is not due, skipping`. I also noticed that when I execute `ark schedule get` that my Schedule is initally in ENABLED status, and changes to NEW after I deployed a second time. 

My own hypothesis : my yaml deployment of the schedule is the key for this not working? (I generated it with ark with a command line with something like  `ark create schedule... -o yaml`.... see here the output here: https://github.com/mmuth/ark-schedule-repro/blob/master/deploy/schedule.yaml).

**Comment by ncdc** [comment] 2019-01-22 18:24
It sounds like this is what's happening:

1. yaml schedule doesn't have status.phase set (which is correct)
1. the first `apply` creates the schedule
1. the schedule controller processes the schedule and changes the phase to enabled
1. the second `apply` resets the status.phase back to empty/new
1. the schedule controller only processes schedules that have been newly added, and doesn't look at modifications, so it doesn't change the phase from empty/new to enabled

There are 2 possible fixes:

1. If your Kubernetes version has the `CustomResourceSubresources` feature gate enabled (alpha in v1.10, beta and enabled by default in v1.11 and newer), then the apiserver will automatically disallow the `apply` from mutating `status`, meaning the phase won't get changed.
1. We create some combination of validating and/or mutating webhooks that either fail the `apply` (undesirable) or mutate the incoming update to disallow status changes.

Fix 1 is preferable from our end, but it has Kubernetes version/feature gate requirements.

cc @rosskukulinski, xref #596

**Comment by skriss** [comment] 2019-06-25 15:04
xref #529

**Comment by skriss** [comment] 2019-06-25 15:06
I'm closing this issue as essentially a dupe of #529. Before making that change we need to consider the implications on our minimum supported Kubernetes version, per #596.

**Closed by skriss** 2019-06-25 15:06 UTC
