### ISSUE TITLE
Add JSON schema validation for Ark's custom resources

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#155] opened 2017-10-26 15:16 UTC
See https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation for more details.

It's an alpha feature in Kubernetes 1.8, and must be enabled by the cluster administrator for the apiserver. We therefore can't rely on it right now, but it's worth having so that once this feature is enabled by default, we can.

**Comment by nikhita** [comment] 2017-10-27 13:34
@ncdc I noticed the `help wanted` label on this issue. Can I take it up once it's moved to beta (https://github.com/kubernetes/kubernetes/issues/53829) and enabled by default? :smile:

**Comment by ncdc** [comment] 2017-10-27 13:43
@nikhita yes please!!! We'd actually love it if you wanted to do it sooner, as like I wrote above, we won't require that it be there until it's enabled by default, but we'd like to take advantage of it if we can. Thanks!

**Comment by nikhita** [comment] 2018-03-02 03:59
If this is still open, I can come back to this after some days. But @munnerz has a PR open upstream for generating the schema -- if we could get it in and generate using that, it would be awesome. :)

**Comment by rosskukulinski** [comment] 2018-06-20 00:55
From #492:

We should test whether JSON schema validation will help when creating `DeleteBackupRequest` objects.  Ark CLI should return a helpful error message when trying to create objects with invalid names.

e.g.

```
If I query for logs from a backup with an upper case name, I get a confusing error:
$ ark backup logs Invalid
An error occurred: DownloadRequest.ark.heptio.com "Invalid-20180515125158" is invalid: metadata.name: Invalid value: "Invalid-20180515125158": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

If the validation does not, then we need to create a separate issue to add that capability.

**Comment by skriss** [comment] 2019-07-22 16:12
xref #1675

**Comment by cblecker** [comment] 2019-08-08 00:19
xref #1267 (kubebuilder has autogeneration of openapi validation: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html)

**Comment by prydonius** [comment] 2019-09-10 18:24
think this is a dupe of #1675, shall we close it out?

**Comment by skriss** [comment] 2019-09-10 18:43
Yep OK reviewed and agree this is a dupe and #1675 is more up-to-date. Closing.

**Closed by skriss** 2019-09-10 18:43 UTC
Labels: Enhancement/Dev, Help wanted, P1 - Important
